

ALTER TABLE `OPENBOOK`.`openbook_detail` 
ENGINE=MyISAM
 PARTITION BY LIST(detail_id) 
 (
 PARTITION p0 VALUES IN (0),
 PARTITION p1 VALUES IN (1),
 PARTITION p2 VALUES IN (2),
 PARTITION p3 VALUES IN (3),
 PARTITION p4 VALUES IN (4),
 PARTITION p5 VALUES IN (5),
 PARTITION p6 VALUES IN (6),
 PARTITION p7 VALUES IN (7),
 PARTITION p8 VALUES IN (8),
 PARTITION p9 VALUES IN (9)
 )
