SET @SA=0.01;
SET @SB=0.01;
SET @SAB=0.001;
SET @v=3;

SET @SA_CRITERIA='ABOVE_EQUAL'; 
SET @SB_CRITERIA='ABOVE';
SET @SAB_CRITERIA='BELOW';
SET @V_CRITERIA='BELOW_EQUAL';

SET @ASK_PRICE=0; -- 0 TOP ... 9 BOT
SET @BID_PRICE=0; 

SET @DISTANCE=30; -- distance between ticksOpenbook_partition